server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://user:123456@eureka1:8761/eureka/,http://user:123456@eureka2:8762/eureka/